### ISSUE TITLE
Analytics view [all] show text and descriptions and empty graphs

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#54]
**Issue:**
* Analytics view [all] show text and descriptions and empty graphs

**Fix:**
* Export the react stuff that creates the analytic card as it's own component
* In the component have an empty state if no data exists in the props

**Branch:**
* fix/analytics

**Comment by AbBaSaMo** [comment]
Empty state has been added. Improvements need to be made to UI so that there is one feedback message per analytic card vs one per graph
