### ISSUE TITLE
Import CSV columns need to be updated to what’s needed

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#57]
**Issue:** 
* Import CSV columns need to be updated to what’s needed

**Fix:**
* Literally just what is needed for that feature
* Ask Rio if this app is just for monash or anyone

**Branch:**
* refactor/import-csv

**Comment by AbBaSaMo** [comment]
Users can now upload CSVs with any arbitrary additional column headings as long as the required rows and headings are supplied.
Included in the relevant PR are general refactors and other fixes including improved navigation and UI.
