### ISSUE TITLE
Confirmation dialogues

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#59]
**Issue:**
* Dialogue asking if you are sure about deleting a student from a unit within the students list page
* Dialogue asking if you are sure about moving a student to a group in a different lab

**Branch:**
* refactor/unit-dashboard

**Comment by AbBaSaMo** [comment]
Opened as separate issues, closing this one https://github.com/Monash-FIT3170/BaLance-Team-Forming-Dashboard/issues/99 https://github.com/Monash-FIT3170/BaLance-Team-Forming-Dashboard/issues/100
