### ISSUE TITLE
Feedback/guide in form groups page and csv upload

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#60]
**Issue:**
* Feedback/guide in csv upload pages 

**Fix:** 
* Show some sort of visualisation of the fields a csv should have

**Branch:**
* refactor/import-csv

**Issue:**
* Feedback/guide in create groups page

**Fix:** 
* Rewrite the descriptive paragraphs for each feature on the page to make it more obvious what is required

**Branch:**
* fix/refactor-create-groups

**Comment by AbBaSaMo** [comment]
CSV info button currently dynamically lists the different header requirements based on what the user selects to upload in ImportPage.jsx as part of https://github.com/Monash-FIT3170/baLance/pull/74

What remains include

- updates to guide in create groups
- potential re-evaluation of how current guide on CSV headers is presented to user in ImportPage.jsx
