### ISSUE TITLE
Improve UI navigation components

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#63]
**Issue:**
* UI components for navigating around the app could be improved e.g. in csv upload pages 

**Fix:**
* Remove the "continue to dashboard" button. Have the page automatically navigate when the user **successfully** imports something 

**Branch:**
* refactor/import-csv

**Comment by AbBaSaMo** [comment]
UI components have been updated as part of improvements in refactor/import-csv
Automatic navigation on saving import is no longer desired. Instead we can ask the user if they would like to navigate back or stay to upload more data via modal or such prompt.

**Comment by AbBaSaMo** [comment]
Page now clears the table preview of import data on saving and allows user to add more data or otherwise navigate back to the dashboard.
