### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#65]
**Issue:**
*  Both the unit card and the title are clickable but do the same thing i.e. navigate to the units page
* Unit cards align in 2 columns rather than 3 columns in certain screen sizes

**Fix:**
* Make the title unclickable

**Branch:**
* feature/unit-home-page

**Comment by AbBaSaMo** [comment]
Fix has been merged into main
