### ISSUE TITLE
Upload buttons are not clickable in places that have text in them

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#68]
**Issue:** 
* Upload buttons are not clickable in places that have text in them

**Fix:**
* Moving the text outside is a fix but Rio does not like this
* Could potentially implement something like this: https://files.slack.com/files-tmb/T04TL60581H-F05SKS15V7A-4eeac5db24/image_720.png

**Branch:**
* refactor/import-csv

**Comment by Mark-Mikhail** [comment]
- Issue ready to be closed. Added 'Drop file here or 'select; file from folder' to disntinguish between drag and drop.
