### ISSUE TITLE
Filter the units in the frontend

### ISSUE THREAD

**Issue by mfin0008** [Monash-FIT3170/BaLance-Team-Forming-Dashboard#70]
**Issue:**
* On the unit homepage, we want users to be able to filter out units which are no longer active if they want to 
* The units should also have the ability to be sorted by earliest start date - latest or vice versa

**Fix:**
* Drop down is the easiest view and sort by year
* Will need a way to track when a unit is no longer active though so either a button the user clicks or a timer

**Branch:**
* feature/unit-home-page

**Comment by jon65** [comment]
fix:
1. drop down list for sorting units by ascending or descending order of dates
2. drop down list for displaying units (display active units only or all units)
